version: '3.1'

services:
  localhost:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Castillo0*
      MYSQL_DATABASE: Proyeto_final
      MYSQL_USER: root
      MYSQL_PASSWORD: Castillo0*

  app:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Castillo0*
      - DB_NAME=Proyeto_final
    ports:
      - "9000:9000"
    depends_on:
      - db
